[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
# This is *critical* to ensure that gitleaks runs rules, unless you provide your own comprehensive rule list!
useDefault = true

[allowlist]
description = "Allowlist for false positives"

[[rules]]
id = "hashicorp-tf-password"
description = "Identified a HashiCorp Terraform password field, risking unauthorized infrastructure configuration and security breaches."
regex = '''(?i)(?:administrator_login_password|password)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}("[a-z0-9=_\-]{8,20}")(?:['|\"|\n|\r|\s|\x60|;]|$)'''
keywords = [
    "administrator_login_password","password",
]

[rules.allowlist]
regexTarget = "line"
regexes = [
  # justification: the certificateKeystorePassword is an old password for a dev certificate. This certificate has been removed, along with the SSL options
  # from Tomcat's server.xml file.
  "certificateKeystorePassword",
]
