
FROM golang:1.18.1-alpine3.15 as build

WORKDIR /app

COPY go.mod ./

RUN apk add git && \
    go mod download

COPY . ./

RUN go build -o /app/bin/ ./...


FROM golang:1.18.1-alpine3.15

ENV KNIGHT_LIGHT_PORT 8080

WORKDIR /app

COPY --from=build /app/bin/knight-light-server .

EXPOSE 8080

CMD [ "/app/knight-light-server" ]
