pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        restartPolicy: Never
        containers:
        - name: go
          image: artifactory.cloud.cms.gov/docker/golang:1.22-alpine
          command: ['tail', '-f', '/dev/null']
      """
    }
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '10'))
    copyArtifactPermission('*');
  }

  stages {
    stage('Build') {
      steps {
        container('go') {
          dir('go-server') {
            sh 'go build ./...'
          }
        }
      }
    }

    stage ('Test') {
      steps {
        container('go') {
          dir('go-server') {
            sh 'go test -coverprofile=coverage.out ./...'
            archiveArtifacts artifacts: "coverage.out", allowEmptyArchive: true
          }
        }
      }
    }

    stage('SAST') {
      steps {
        script {
          def sastParameters = [
            string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
            string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
            string(name: 'git_commit', value: "${GIT_COMMIT}"),
            string(name: 'git_branch', value: "${env.GIT_BRANCH}"),
            string(name: 'copy_artifacts_job_name', value: "${env.JOB_NAME}"),
            string(name: 'copy_artifacts_build_number', value: "${env.BUILD_NUMBER}"),
            string(name: 'copy_artifacts_filter', value: 'coverage.out')
          ]

          if (env.CHANGE_ID) {
            sastParameters.add(string(name: 'git_change_id', value: "${env.CHANGE_ID}"))
          }

          build(job: 'Go Server SAST', wait: true, propagate: true, parameters: sastParameters)
        }
      }
    }

    stage('Delivery') {
      steps {
        build(job: 'Go Server Delivery', wait: true, propagate: true, parameters: [
          string(name: 'tag', value: "${GIT_COMMIT[0..7]}"),
          string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
          string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
          string(name: 'git_commit', value: "${GIT_COMMIT}"),
          string(name: 'build_dir', value: 'go-server'),
          string(name: 'dockerfile', value: 'go-server/Dockerfile'),
        ])
      }
    }
  }
}
