variables:
  TEMPLATE_VERSION: "v1"
  TARGET_ENVIRONMENT: "impl"
  LINT_SOURCE_DIR: "src"

stages:
  - ci
  - deliver
  - release
  - deployment

ci-pipeline:
  stage: ci
  trigger:
    strategy: depend
    include:
      - project: 'devops-pipelines/pipeline-triggers'
        ref: ${TEMPLATE_VERSION}
        file: 'ci/python.yaml'

delivery-pipeline:
  stage: deliver
  variables:
    PUSH_LATEST: "true"
  trigger:
    strategy: depend
    include:
      - project: 'devops-pipelines/pipeline-triggers'
        ref: ${TEMPLATE_VERSION}
        file: 'delivery.yaml'

release-pipeline:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  trigger:
    strategy: depend
    include:
      - project: 'devops-pipelines/pipeline-triggers'
        ref: ${TEMPLATE_VERSION}
        file: 'release.yaml'

deployment-pipeline:
  stage: deployment
  trigger:
    strategy: depend
    include:
      - project: 'devops-pipelines/pipeline-triggers'
        ref: ${TEMPLATE_VERSION}
        file: 'deployment.yaml'

