pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        restartPolicy: Never
        containers:
        - name: build
          image: artifactory.cloud.cms.gov/docker/node:18
          command: ['tail', '-f', '/dev/null']
      """
    }
  }

  environment {
    IMAGE_NAME = 'artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/jenkins-knight-light/node-server'
    IMAGE_TAG = "${TAG_NAME ?: GIT_COMMIT[0..7]}"
    ENABLE_PUBLISH = "${TAG_NAME ? true : (GIT_BRANCH == 'main')}"
  }

  stages {
    stage('Build') {
      steps {
        container('build') {
          dir('node-server') {
            sh 'npm ci'
          }
        }
      }
    }

    stage('Test') {
      parallel {
        stage('Unit Test') {
          steps {
            container('build') {
              dir('node-server') {
                sh 'npm run test:unit'
              }
            }
          }
        }
        stage('Lint') {
          steps {
            container('build') {
              dir('node-server') {
                sh 'npm run lint'
              }
            }
          }
        }
        stage('SAST') {
          steps {
            script {
              def sastParameters = [
                string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
                string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
                string(name: 'git_commit', value: "${GIT_COMMIT}"),
                string(name: 'git_branch', value: "${env.GIT_BRANCH}"),
              ]

              if (env.CHANGE_ID) {
                sastParameters.add(string(name: 'git_change_id', value: "${env.CHANGE_ID}"))
              }

              build(job: 'Node Server SAST', wait: true, propagate: true, parameters: sastParameters)
            }
          }
        }
      }
    }

    stage('Delivery') {
      steps {
        build(job: 'Node Server Delivery', wait: true, propagate: true, parameters: [
          string(name: 'image', value: "${env.IMAGE_NAME}"),
          string(name: 'tag', value: "${env.IMAGE_TAG}"),
          string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
          string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
          string(name: 'git_commit', value: "${GIT_COMMIT}"),
          booleanParam(name: 'image_push_enabled', value: env.ENABLE_PUBLISH == 'true')
        ])
      }
    }

    stage('Deploy Dev') {
      when {
        branch 'main'
      }
      steps {
        build(job: 'Node Server Deployment', wait: true, propagate: true, parameters: [
          string(name: 'image', value: "${env.IMAGE_NAME}"),
          string(name: 'tag', value: "${env.IMAGE_TAG}")
        ])
      }
    }

    stage('Deploy Test') {
      when {
        tag pattern: 'v[0-9.]+(-.*)?', comparator: 'REGEXP'
      }
      steps {
        build(job: 'Node Server Deployment', wait: true, propagate: true, parameters: [
          string(name: 'image', value: "${env.IMAGE_NAME}"),
          string(name: 'tag', value: "${env.IMAGE_TAG}"),
          string(name: 'environment_path', value: 'test')
        ])
      }
    }
  }
}
