# Use the official PHP image as a base
# FROM php:8.2.20-fpm-alpine3.20
FROM artifactory.cloud.cms.gov/docker/drupal:php8.3-fpm-alpine3.20 AS fpm-shared-dev

# Set the working directory
WORKDIR /var/www/html

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy the application files
COPY . .

# Install dependencies
RUN ls -ltr
RUN pwd
RUN which composer
RUN composer install --no-progress --no-interaction --no-dev --optimize-autoloader

# Expose the port on which the app will run
EXPOSE 80

# Command to run the application
CMD ["php", "-S", "0.0.0.0:80", "-t", "."]