variables:
  TEMPLATE_VERSION: "v1"
  TARGET_ENVIRONMENT: "impl"

ci-pipeline:
  needs: []
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "ci/npm.yaml"

sast-pipeline:
  needs: []
  variables:
    SCAN_GITLEAKS: "true"
    SCAN_SEMGREP: "true"
    SEMGREP_RULES_ADD: "p/javascript"
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "sast.yaml"

delivery-pipeline:
  needs: [ "sast-pipeline" ]
  variables:
    FETCH_CI_ARTIFACTS: "true"
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "delivery.yaml"

deployment-pipeline:
  needs: [ "delivery-pipeline" ]
  variables:
    FETCH_SAST_ARTIFACTS: "true"
    PUSH_LATEST: "true"
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "deployment.yaml"

