pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        restartPolicy: Never
        containers:
        - name: build
          image: artifactory.cloud.cms.gov/docker/node:20-alpine
          command: ['tail', '-f', '/dev/null']
      """
    }
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '100'))
  }

  stages {
    stage('Build') {
      steps {
        container('build') {
          dir('ui') {
            sh 'npm ci && npm run build'
          }
        }
      }
    }

    stage('Test') {
      parallel {
        stage('Unit Test') {
          steps {
            container('build') {
              dir('ui') {
                sh 'npm run test'
              }
            }
          }
        }
        stage('Lint') {
          steps {
            container('build') {
              dir('ui') {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE', message: '[WARNING] Lint issues detected!') {
                  sh 'npm run lint'
                }
              }
            }
          }
        }
        stage('SAST') {
          steps {
            script {
              def sastParameters = [
                string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
                string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
                string(name: 'git_commit', value: "${GIT_COMMIT}"),
                string(name: 'git_branch', value: "${env.GIT_BRANCH}"),
              ]

              if (env.CHANGE_ID) {
                sastParameters.add(string(name: 'git_change_id', value: "${env.CHANGE_ID}"))
              }

              build(job: 'UI SAST', wait: true, propagate: true, parameters: sastParameters)
            }
          }
        }
      }
    }

    stage('Delivery') {
      steps {
        build(job: 'UI Delivery', wait: true, propagate: true, parameters: [
          string(name: 'tag', value: "${GIT_COMMIT[0..7]}"),
          string(name: 'git_repository', value: "${scm.userRemoteConfigs[0].url}"),
          string(name: 'git_credentials', value: "${scm.userRemoteConfigs[0].credentialsId}"),
          string(name: 'git_commit', value: "${GIT_COMMIT}"),
          string(name: 'build_dir', value: 'ui'),
          string(name: 'dockerfile', value: 'ui/Dockerfile')
        ])
        container('build') {
          echo 'Child pipeline completed'
        }
      }
    }
  }
}
