name: Build Apps
run-name: Building each server and UI
on: [push]
jobs:
  Build-Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          cd java-server
          mvn clean install
  Build-Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: Build with Go
        run: |
          cd go-server
          go mod tidy
          go build
  Build-Node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd nodeJs-server
          npm ci
