name: Build Knight-Light Go Server
on: [push, workflow_dispatch]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/build-image@wip-build-image-action
        with:
          path: ./go-server/
          # TODO: the dockerfile path should be relative to the context path
          dockerfile: ./go-server/Dockerfile
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: cms-enterprise/batcave/knight-light-go-server:testing
          repo_token: ${{ secrets.GITHUB_TOKEN }}
