on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: Name to use when tagging the container image (e.g. `my-app:latest`)
      build_dir:
        type: string
        description: The directory of the project being built
      artifact_dir:
        type: string
        description: artifact directory for reports
        default: artifacts

jobs:
  build_scan_publish_image:
    runs-on: ["batcave-runners"]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-40afc230

    steps:
      - uses: actions/checkout@v4
      - name: Image Build
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-build-podman@feat/podman-as-root
        with:
          build_dir: "${{ inputs.build_dir }}"
          dockerfile: "${{ inputs.build_dir }}/Dockerfile"
          tag: ${{ inputs.image_tag }}

      - name: Image Scan
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-scan-podman@feat/podman-as-root
        with:
          tag: ${{ inputs.image_tag }}
          artifact_dir: ${{ inputs.artifact_dir }}
      - name: Image Publish
        uses: docker://ghcr.io/cms-enterprise/batcave/workflow-engine:podman-40afc230
        with:
          entrypoint: /bin/sh
          # Note: github-entrypoint.sh version; has an important side effect: modifying the podman
          # configuration to use the shared container storage location
          args: >-
            -c '
            github-entrypoint.sh version;
            export TEMP_IMAGE_TAG="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m";
            export BUNDLE_TAG="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m";
            su podman -s /bin/sh -c "podman image ls";
            su podman -s /bin/sh -c "podman tag ${{ inputs.image_tag }} $TEMP_IMAGE_TAG";
            github-entrypoint.sh run image-publish --tag $TEMP_IMAGE_TAG --bundle-tag $BUNDLE_TAG --artifact-dir $OUT_ARTIFACT_DIR -i podman'

      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: ${{ github.workspace }}/artifacts
