on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: image tag to update in manifest

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.MANIFEST_DEPLOY_TOKEN }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $$SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions

      - name: Pull Manifest
        shell: sh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config --global user.email "githubactions@cms.hhs.gov"
          git config --global user.name "Github Actions"
          git clone git@github.com:CMS-Enterprise/batcave-knight-light-manifest.git
          ls -la

      - uses: imranismail/setup-kustomize@v2
      - run: |-
          kustomize version
          ls -la
           cd batcave-knight-light-manifest
          kustomize edit set image ${{ inputs.image_tag}}
          git commit -am "Set image tag as ${{ inputs.image_tag }}"
          git push