on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: image tag to update in manifest

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: imranismail/setup-kustomize@v2
      - run: |-
          kustomize version
          git checkout https://github.com/CMS-Enterprise/batcave-knight-light-manifest.git
          kustomize edit set image ${{ inputs.image_tag}}
          git add .
          git commit -m "Set image tag as ${{ inputs.image_tag }}"
          git push