on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: image tag to update in manifest

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: imranismail/setup-kustomize@v2
      - run: |-
          kustomize version