name: Build Knight-Light Go Server
run-name: "Build Knight-Light Go Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: Build with Go
        run: |
          cd go-server
          go mod tidy
          go build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: Test with Go
        run: |
          cd go-server
          go test ./... -v -short
  delivery:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO combine all delivery jobs into a single action
      - name: Build container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-build@wip-build-image-action
        with:
          path: ./go-server/
          # TODO: the dockerfile path should be relative to the context path
          dockerfile: ./go-server/Dockerfile
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: cms-enterprise/batcave/knight-light-go-server:testing
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-scan@wip-build-image-action
        with:
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: cms-enterprise/batcave/knight-light-go-server:testing
          output_dir: ./artifacts
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-results
          path: ./artifacts/*.json
          if-no-files-found: error
