name: Build Knight-Light Go Server
run-name: "Build Knight-Light Go Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Build with Go
        run: |
          cd go-server
          go mod tidy
          go build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - run: |
          cd go-server
          go test ./... -v -short


  code-scan:
    uses: ./.github/workflows/code-scan.yml
    with:
      src_dir: ./go-server

  vars:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAG_NAME=${GITHUB_REF/refs\/tags\//}
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Output the tag
        run: |
          echo "The tag name is ${tag_name}"
        env:
          tag_name: ${{ steps.vars.outputs.tag_name }}

  image-delivery:
    needs: vars
    uses: ./.github/workflows/delivery.yml
    with:
      image_tag: ghcr.io/cms-enterprise/batcave/knight-light-go-server:${{ needs.vars.outputs.tag_name }}
      build_dir: ./go-server

