name: Build Knight-Light Go Server
run-name: "Build Knight-Light Go Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Build with Go
        run: |
          cd go-server
          go mod tidy
          go build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - run: |
          cd go-server
          go test ./... -v -short

  workflow_engine:
    runs-on: ubuntu-latest
    name: Run Workflow Engine
    outputs:
      full_image_tag: ${{ steps.vars.outputs.full_image_tag }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo full_image_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
          echo full_bundle_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
      - name: Run Workflow Engine
        uses: cms-enterprise/batcave-workflow-engine-action@main
        with:
          build_dir: "go-server"
          dockerfile: "go-server/Dockerfile"
          tag: ${{ steps.vars.outputs.full_image_tag }}
          bundle_publish_tag: ${{ steps.vars.outputs.full_bundle_tag }}

      - name: Clone Manifest
        uses: actions/checkout@v4
        with:
          repository: CMS-Enterprise/batcave-knight-light-manifest
          ssh-key: ${{ secrets.MANIFEST_DEPLOY_TOKEN }}

  deploy_impl:
    runs-on: ubuntu-latest
    needs: workflow_engine
    concurrency:
      group: "manifest-repo-access"
    steps:
      - uses: imranismail/setup-kustomize@v2
      - run: |
          kustomize version
          cd /home/runner/work/batcave-knight-light/batcave-knight-light
          git config --global user.email "githubaction@cms.hhs.gov"
          git config --global user.name "Github Action"
          cd impl
          kustomize edit set image knight-light-server-go=${{ needs.workflow_engine.outputs.full_image_tag }}
          git commit -am "[deploy] set knight-light-server-go image tag on impl to ${{ needs.workflow_engine.outputs.full_image_tag }}"
          git push
