name: Build Knight-Light Go Server
run-name: "Build Knight-Light Go Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

env:
  WORKFLOW_ENGINE_VERSION: v0.0.1-rc.10

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      WORKFLOW_ENGINE_VERSION: ${{ steps.output.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - id: output
        run: |
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}"
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}" >> $GITHUB_OUTPUT

  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Build with Go
        run: |
          cd go-server
          go mod tidy
          go build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Test with Go
        run: |
          cd go-server
          go test ./... -v -short

  code-scan:
    runs-on: ubuntu-latest
    needs: [set-version]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ needs.set-version.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - shell: sh
        run: |- 
          git config --global --add safe.directory /__w/batcave-knight-light/batcave-knight-light
          cd go-server
          mkdir -p .artifacts
          workflow-engine run code-scan --semgrep-experimental

  image-delivery:
    uses: ./.github/workflows/delivery.yaml
    with:
      image_tag: ghcr.io/cms-enterprise/batcave/knight-light-go-server
      build_dir: ./go-server

