name: Build Knight-Light Java Server
run-name: "Build Knight-Light Java Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          cd java-server
          mvn clean install

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn clean test

  workflow_engine:
    runs-on: ["batcave-runners"]
    container: ghcr.io/cms-enterprise/batcave/workflow-engine-action:podman-v0.0.1-rc.16
    name: Run Workflow Engine
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo full_image_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
          echo full_bundle_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
      - name: Run Workflow Engine
        uses: cms-enterprise/batcave-workflow-engine-action/image-build-scan-publish/podman@feat/podman-support
        with:
          build_dir: "java-server"
          dockerfile: "java-server/Dockerfile"
          tag: ${{ steps.vars.outputs.full_image_tag }}
          bundle_publish_tag: ${{ steps.vars.outputs.full_bundle_tag }}
