name: Build Knight-Light Java Server
run-name: "Build Knight-Light Java Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          cd java-server
          mvn clean install
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn clean test
  delivery:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO combine all delivery jobs into a single action
      - name: Build container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-build@main
        with:
          path: ./java-server/
          # TODO: the dockerfile path should be relative to the context path
          dockerfile: ./java-server/Dockerfile
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: cms-enterprise/batcave/knight-light-java-server:testing
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-scan@main
        with:
          image_tag: cms-enterprise/batcave/knight-light-java-server:testing
          output_dir: ./artifacts
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-results
          path: ./artifacts/*.json
          if-no-files-found: error
