name: Build Knight-Light Java Server
run-name: "Build Knight-Light Java Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          cd java-server
          mvn clean install

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn clean test

  code-scan:
    uses: ./.github/workflows/code-scan.yml
    with:
      src_dir: ./java-server

  vars:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAG_NAME=${GITHUB_REF/refs\/tags\//}
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Output the tag
        run: |
          echo "The tag name is ${tag_name}"
        env:
          tag_name: ${{ steps.vars.outputs.tag_name }}

  image-delivery:
    needs: vars
    uses: ./.github/workflows/delivery.yml
    with:
      image_tag: ghcr.io/cms-enterprise/batcave/knight-light-java-server:${{ needs.vars.outputs.tag_name }}
      build_dir: ./java-server
