name: Build Knight-Light Java Server
run-name: "Build Knight-Light Java Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

env:
  WORKFLOW_ENGINE_VERSION: v0.0.1-rc.4
  OUTPUT_DIR: ./artifacts
  WORKING_DIR: $GITHUB_WORKSPACE/java-server

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'corretto'
  #         cache: maven
  #     - name: Build with Maven
  #       run: |
  #         cd java-server
  #         mvn clean install
  set-version:
    runs-on: ubuntu-latest
    outputs:
      WORKFLOW_ENGINE_VERSION: ${{ steps.output.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - id: output
        run: |
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}"
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn clean test
  # delivery:
  #   needs: [build, test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     # TODO combine all delivery jobs into a single action
  #     - name: Build container image
  #       uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-build@main
  #       with:
  #         path: ./java-server/
  #         # TODO: the dockerfile path should be relative to the context path
  #         dockerfile: ./java-server/Dockerfile
  #         # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
  #         image_tag: cms-enterprise/batcave/knight-light-java-server:testing
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Scan container image
  #       uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-scan@main
  #       with:
  #         image_tag: cms-enterprise/batcave/knight-light-java-server:testing
  #         output_dir: ./artifacts
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Archive image scan outputs
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: image-scan-results
  #         path: ./artifacts/*.json
  #         if-no-files-found: error
  sast:
    runs-on: ubuntu-latest
    needs: [set-version]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ needs.set-version.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - shell: sh
        run: |-
          git config --global --add safe.directory /__w/batcave-knight-light/batcave-knight-light
          cd java-server
          mkdir -p .artifacts
          workflow-engine run code-scan --semgrep-experimental

  delivery:
    runs-on: ubuntu-latest
    needs: [set-version]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ needs.set-version.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Image Build
        shell: sh
        run: |-
          cd java-server
          workflow-engine run image-build --tag java-server-image
      - name: Image Scan
        shell: sh
        run: |-
          cd java-server
          mkdir -p .artifacts
          workflow-engine run image-scan --artifact-directory .artifacts --grype-filename grype-scan.json --sbom-filename syft-sbom.json --scan-image-target java-server-image
          ls -la .artifacts
      - name: Image Publish
        shell: sh
        run: |-
          cd java-server
          ls -la .artifacts
          workflow-engine run image-publish
