name: Build Knight-Light NodeJS Server
run-name: "Build Knight-Light NodeJS Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd node-server
          npm ci

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd node-server
          npm ci
          npm run test:unit

  workflow_engine:
    runs-on: ["batcave-runners-dev-paul"]
    container: ghcr.io/cms-enterprise/batcave/workflow-engine-action:podman-v0.0.1-rc.3
    name: Run Workflow Engine
    steps:
      - uses: actions/checkout@v4
      - name: Run Workflow Engine
        uses: cms-enterprise/batcave-workflow-engine-action/image-build-scan-publish/podman@feat/podman-support
        with:
          build_dir: "node-server"
          dockerfile: "node-server/Dockerfile"
          tag: "artifactory.cloud.cms.gov/batcave-docker/pwheeler/workflow-engine-testing/batcave-knight-light/node-server:latest"
          bundle_publish_tag: "artifactory.cloud.cms.gov/batcave-docker/pwheeler/workflow-engine-testing/batcave-knight-light/node-server/scan-reports:latest"
          container_registry: "artifactory.cloud.cms.gov"
          registry_user: ${{ vars.CONTAINER_REGISTRY_USER }}
          registry_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
