name: Build Knight-Light NodeJS Server
run-name: "Build Knight-Light NodeJS Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd nodeJs-server
          npm ci

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd nodeJs-server
          npm ci
          npm run test:unit

  code-scan:
    uses: ./.github/workflows/code-scan.yml
    with:
      src_dir: ./nodeJs-server

  vars:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAG_NAME=${GITHUB_REF/refs\/tags\//}
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Output the tag
        run: |
          echo "The tag name is ${tag_name}"
        env:
          tag_name: ${{ steps.vars.outputs.tag_name }}

  image-delivery:
    needs: vars
    uses: ./.github/workflows/delivery.yml
    with:
      image_tag: ghcr.io/cms-enterprise/batcave/knight-light-node-server:${{ needs.vars.outputs.tag_name }}
      build_dir: ./nodeJs-server
