name: Build Knight-Light Python Server
run-name: "Build Knight-Light Python Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with python
        run: |
          cd python-server
          pip install -r requirements.txt
          python -m coverage --version
          python -m coverage run -m pytest
          python -m coverage report
          python -m coverage xml
  delivery:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO combine all delivery jobs into a single action
      - name: Build container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-build@wip-build-image-action
        with:
          path: ./python-server/
          # TODO: the dockerfile path should be relative to the context path
          dockerfile: ./python-server/Dockerfile
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: cms-enterprise/batcave/knight-light-python-server:testing
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan container image
        uses: CMS-Enterprise/batcave-workflow-engine/.github/actions/image-scan@wip-build-image-action
        with:
          image_tag: cms-enterprise/batcave/knight-light-python-server:testing
          output_dir: ./artifacts
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-results
          path: ./artifacts/*.json
          if-no-files-found: error