name: Build Knight-Light Python Server
run-name: "Build Knight-Light Python Server: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with python
        run: |
          cd python-server
          pip install -r requirements.txt
          python -m coverage --version
          python -m coverage run -m pytest
          python -m coverage report
          python -m coverage xml

  code-scan:
    uses: ./.github/workflows/code-scan.yml
    with:
      src_dir: ./python-server

  vars:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAG_NAME=${GITHUB_REF/refs\/tags\//}
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
      - name: Output the tag
        run: |
          echo "The tag name is ${tag_name}"
        env:
          tag_name: ${{ steps.vars.outputs.tag_name }}

  image-delivery:
    needs: vars
    uses: ./.github/workflows/delivery.yml
    with:
      image_tag: ghcr.io/cms-enterprise/batcave/knight-light-python-server:${{ needs.vars.outputs.tag_name }}
      build_dir: ./python-server
