name: Test Apps
run-name: Test each server and UI
on: [push]
jobs:
  Test-Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn clean test
  Test-Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: Test with Go
        run: |
          cd go-server
          go test ./... -v -short        
  Test-Node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd nodeJs-server
          npm ci
          npm run test:unit
  Test-Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versino: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with python
        run: |
          cd python-server
          pip install -r requirements.txt
          python -m coverage --version
          python -m coverage run -m pytest
          python -m coverage report
          python -m coverage xml
  Test-UI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd ui
          npm ci
          npm run test:unit