name: Test Apps
run-name: Test each server and UI
on: [push]
jobs:
  Test-Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Test using Maven and Jacoco
        run: |
          cd java-server
          mvn jacoco:report