name: Build Knight-Light UI
run-name: "Build Knight-Light UI: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd ui
          npm ci

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd ui
          npm ci
          npm run test

  workflow_engine:
    runs-on: ["batcave-runners-dev-paul"]
    container: ghcr.io/cms-enterprise/batcave/workflow-engine-action:podman-v0.0.1-rc.2
    name: Run Workflow Engine
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo full_image_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
          echo full_bundle_tag="ttl.sh/$(cat /proc/sys/kernel/random/uuid):30m" >> $GITHUB_OUTPUT
      - name: Run Workflow Engine
        uses: cms-enterprise/batcave-workflow-engine-action/image-build-scan-publish/podman@feat/podman-support
        with:
          build_dir: "ui"
          dockerfile: "ui/Dockerfile"
          tag: ${{ steps.vars.outputs.full_image_tag }}
          bundle_publish_tag: ${{ steps.vars.outputs.full_bundle_tag }}
