name: Build Knight-Light UI
run-name: "Build Knight-Light UI: ${{ github.event.head_commit.message }}"
on: [push, workflow_dispatch]

env:
  WORKFLOW_ENGINE_VERSION: v0.0.1-rc.4
  OUTPUT_DIR: ./artifacts
  WORKING_DIR: $GITHUB_WORKSPACE/ui

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      WORKFLOW_ENGINE_VERSION: ${{ steps.output.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - id: output
        run: |
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}"
          echo "WORKFLOW_ENGINE_VERSION=${{ env.WORKFLOW_ENGINE_VERSION }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd ui
          npm ci
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Test with Node
        run: |
          cd ui
          npm ci
          npm run test
  delivery:
    runs-on: ubuntu-latest
    needs: [set-version]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ needs.set-version.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Image Build
        shell: sh
        run: |-
          cd ui
          workflow-engine run image-build --tag ui-image
      - name: Image Scan
        shell: sh
        run: |-
          cd ui
          mkdir -p .artifacts
          workflow-engine run image-scan --artifact-directory .artifacts --scan-image-target ui-image
          ls -la .artifacts
      - name: Image Publish
        shell: sh
        run: |-
          cd ui
          ls -la .artifacts
          workflow-engine run image-publish --bundle-directory .artifacts
      - uses: actions/upload-artifact@v4
        with: 
          name: gatecheck-bundle.tar.gz
          path: ui/artifacts/gatecheck-bundle.tar.gz
  
  deploy:
    runs-on: ubuntu-latest
    needs: [set-version, delivery]
    container:
      image: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ needs.set-version.outputs.WORKFLOW_ENGINE_VERSION }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gatecheck-bundle.tar.gz
      - name: Gatecheck Validate
        shell: sh
        run: |-
          ls -la 
          workflow-engine run deploy --artifact-dir .